const pessoas = [
    { nome: "João", sexo: "Masculino", idade: 30 },
    { nome: "Maria", sexo: "Feminino", idade: 25 },
    { nome: "Carlos", sexo: "Masculino", idade: 40 },
    { nome: "Ana", sexo: "Feminino", idade: 35 },
    { nome: "Pedro", sexo: "Masculino", idade: 18 },
    { nome: "Mariana", sexo: "Feminino", idade: 16 },
    { nome: "Lucas", sexo: "Masculino", idade: 22 },
    { nome: "Lara", sexo: "Feminino", idade: 14 },
    { nome: "Fernando", sexo: "Masculino", idade: 28 },
    { nome: "Beatriz", sexo: "Feminino", idade: 32 },
    { nome: "Gustavo", sexo: "Masculino", idade: 17 },
    { nome: "Carolina", sexo: "Feminino", idade: 20 },
    { nome: "Rafael", sexo: "Masculino", idade: 15 },
    { nome: "Sofia", sexo: "Feminino", idade: 23 },
    { nome: "Daniel", sexo: "Masculino", idade: 38 },
    { nome: "Eduardo", sexo: "Masculino", idade: 27 },
    { nome: "Patrícia", sexo: "Feminino", idade: 29 },
    { nome: "André", sexo: "Masculino", idade: 33 },
    { nome: "Camila", sexo: "Feminino", idade: 24 },
    { nome: "Ricardo", sexo: "Masculino", idade: 36 },
    { nome: "Fernanda", sexo: "Feminino", idade: 31 },
    { nome: "Paulo", sexo: "Masculino", idade: 26 },
    { nome: "Vanessa", sexo: "Feminino", idade: 21 },
    { nome: "Felipe", sexo: "Masculino", idade: 19 },
    { nome: "Amanda", sexo: "Feminino", idade: 37 },
    { nome: "Leonardo", sexo: "Masculino", idade: 34 },
    { nome: "Juliana", sexo: "Feminino", idade: 39 },
    { nome: "Hugo", sexo: "Masculino", idade: 42 },
    { nome: "Isabela", sexo: "Feminino", idade: 28 },
    { nome: "Marcos", sexo: "Masculino", idade: 45 },
    { nome: "Laura", sexo: "Feminino", idade: 22 },
    { nome: "Gabriel", sexo: "Masculino", idade: 16 },
    { nome: "Renata", sexo: "Feminino", idade: 24 },
    { nome: "Vinícius", sexo: "Masculino", idade: 29 },
    { nome: "Carla", sexo: "Feminino", idade: 32 },
    { nome: "Alexandre", sexo: "Masculino", idade: 31 },
    { nome: "Tatiane", sexo: "Feminino", idade: 26 },
    { nome: "Marcelo", sexo: "Masculino", idade: 27 },
    { nome: "Natália", sexo: "Feminino", idade: 23 }
];

export { pessoas };